server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rabiloo
    username: root
    password: root
    platform: mysql
    initialization-mode: always
    hikari:
      pool-name: Hikari
      auto-commit: true
      connection-timeout: 600000
      maximum-pool-size: 100
      minimum-idle: 10
      max-lifetime: 1800000
      idle-timeout: 600000
      validation-timeout: 3000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 600
          fetch_size: 600
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 70MB
      max-request-size: 70MB
